services:
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - 9092:9092

  producer:
    build: ./producer
    container_name: kafka-producer
    ports:
      - 9000:9000

  consumer:
    build: ./consumer
    container_name: kafka-consumer
    ports:
    - 9001:9001
    volumes:
      - ./consumer/messages.txt:/consumer/messages.txt
