services:
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
    ports:
      - 9092:9092

  producer:
    build: ./producer
    container_name: kafka-producer
    ports:
      - 9000:9000

  consumer:
    build: ./consumer
    container_name: kafka-consumer
    ports:
    - 9001:9001
    volumes:
      - ./consumer/messages_1.txt:/consumer/messages_1.txt
      - ./consumer/messages_2.txt:/consumer/messages_2.txt
